### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by truefriend-cz** [AkkiaS7/RouterOS-DDNS-Cloudflare#1]
Not found domainid

**Comment by AkkiaS7** [comment]
> Not found domainid

sorry for the late response.

make sure you have already add your domain to Cloudflare DNS dashboard before running this script:
add an A record to the domain you want to set DDNS (for example: set home.example.com 's A record to 1.1.1.1)
and then run the script will change this record automatically associated with the interface you set in this script

**Comment by truefriend-cz** [comment]
Thanks for the response. The problem was with CloudFlare, which is that it blocks the use of APIs for CF, GK, TK, etc. domains, even if the domain is purchased and a tariff is paid for CloudFlare.

They do not accept complaints in this regard. They have a mention of it in the documentation, but it seems that the paid tariff has this unlocked but does not have it. It always blocks these national top level domains.

**Comment by AkkiaS7** [comment]
oops.... that's too bad
